### ISSUE TITLE
Can't fork in a new tab

### ISSUE THREAD

**Issue by jboning** [Artefact2/osmium#76]
I'd like to be able to open the "fork" link in a new tab (so I can flip back and forth and compare my modified version with the original loadout). Since the link is secretly a button that posts a form, this doesn't work.

I don't know if there's any way to get what I want while maintaining CSRF protection.

**Comment by Artefact2** [comment]
Works in Chrome. There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=17754) opened for Firefox and an [extension](https://addons.mozilla.org/en-US/firefox/addon/tabsubmit/) that fixes it.

We could stop using POST, and pass the token in the URI but I'd rather not do that.

**Comment by jboning** [comment]
I love mozilla's 15-year-old bugs. Sigh.

Agreed that passing the token in the URI is suboptimal. And, I guess working around one browser's behaviour is probably not worthwhile. Maybe I'll give that extension a try.
